oslomet-film/Controllers/CartController.cs
using System.Web.Mvc;
using System.Linq;
using oslomet_film.Model;
using oslomet_film.BLL;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace oslomet_film.Controllers
{
    public class CartController : Controller
    {
        public ActionResult AddMovie(int movieID)
        {
            MovieBLL movieBLL = new MovieBLL();
            OrderBLL orderBLL = new OrderBLL();

            Cart cart = GetSessionCart();
            Movie movie = movieBLL.GetMovie(movieID);

            bool ownMovie = false; // False is user not logged in
            // Check if user is logged in
            Customer customer = (Customer)Session["customer"];
            if (customer != null)
            {
                ownMovie = orderBLL.OwnsMovie(customer, movie);
            }

            if (!InCart(movie, cart) || ownMovie)
            {
                CartItem item = new CartItem()
                {
                    Movie = movie,
                    Price = movie.Price
                };
                cart.CartItem.Add(item);
            }
            
            ViewBag.Total = GetTotal();
            return PartialView("CartPartial", cart.CartItem.ToList());
        }
        public ActionResult CompleteOrder()
        {
            OrderBLL orderBLL = new OrderBLL();

            Customer customer = (Customer)Session["customer"];
            if(customer == null)
            {
                // User must be logged in
                return null;
            }

            orderBLL.CreateOrder(customer, GetSessionCart());
            Session["cart"] = null;
            return Content("Success");
        } 

        public ActionResult GetCart()
        {
            ViewBag.Total = GetTotal();
            Cart cart = GetSessionCart();
            return PartialView("CartPartial", cart.CartItem.ToList());
        }

        public ActionResult GetCartFull()
        {
            Cart cart = GetSessionCart();
            ViewBag.Total = GetTotal();
            return View(cart.CartItem.ToList());
        }

        //Removing item from CartItems List in Cart
        public ActionResult RemoveItem(int movieID)
        {
            Cart cart = GetSessionCart();
            cart.CartItem.RemoveAll(ci => ci.Movie.ID == movieID);
            return View("index", GetSessionCart());
        }
        

        // GET: Cart
        public ActionResult Index()
        {
            ViewBag.Total = GetTotal();
            return View(GetSessionCart());
        }

        public Cart GetSessionCart()
        {
            Cart cart = (Cart)Session["cart"];

            if (cart != null) {
                return cart;
            }

            cart = new Cart
            {
                CartItem = new List<CartItem>()
            };
            Session["cart"] = cart;
            return cart;
        }

        private int GetTotal()
        {
            int total = 0;
            Cart cart = GetSessionCart();
            foreach(CartItem item in cart.CartItem) {
                total += item.Price;
            }
            return total;
        }

        
        private bool InCart(Movie movie, Cart cart)
        {
            foreach(CartItem item in cart.CartItem)
            {
                if (item.Movie.ID == movie.ID) return true;
            }
            return false;
        }
    }
}

oslomet-film/Controllers/MovieController.cs
using System.Web.Mvc;
using oslomet_film.Model;
using oslomet_film.BLL;
using System.Collections.Generic;

namespace oslomet_film.Controllers
{
    public class MovieController : Controller
    {
        public ActionResult FilterMovies(int categoryID)
        {
            var movieBLL = new MovieBLL();
            List<Movie> movies = movieBLL.FilterMovies(categoryID);
            return PartialView("MovieList", movies);
        }

        public Movie GetMovie(int movieID)
        {
            var movieBLL = new MovieBLL();
            return movieBLL.GetMovie(movieID);
        }

        // Dette viewet må gjøres om til enten en collapse eller en popup!!!
        public ActionResult Details(int movieID)
        {
            var movieBLL = new MovieBLL();
            Movie movie = movieBLL.GetMovie(movieID);
            //Gjør om til partial
            return View(movie);
        }
    }
}

oslomet-film/Views/Movie/Details.cshtml
@model oslomet_film.Model.Movie


<br /><br /><br />

    <div class="col-md-3">
        <img class="thumbnail-lg" src="@Model.Thumbnail" />
    </div>
    <div class="col-md-6">
        <h2>@Model.Title</h2>
        <br />
        <p>@Model.Description</p>
    </div>
    <div class="col-md-3">
        <a href="@Url.Action("BuyNow", "Movie", new { movieID = Model.ID})" class="btn btn-primary btn-block" id="#">
            Buy/Rent now
        </a>
        <br />
        <a href="@Url.Action("AddItem", "Cart", new { movieID = Model.ID})" class="btn btn-primary btn-block" id="#">
            Add To Cart
        </a>
        <a href="@Url.Action("GetCartFull", "Cart", new { movieID = Model.ID})" class="btn btn-primary btn-block" id="#">
            Go to cart
        </a>
    </div>

oslomet-film/Views/Movie/MovieList.cshtml
@model System.Collections.Generic.List<oslomet_film.Model.Movie>

<div class="row" id="movies">
    @foreach (var movie in Model)
    {
        <div class="col-md-3 col-sm-6">
                <div class="movie-thumbnail" style="background-image: url('@movie.Thumbnail')">
                    <div class="movie-hover" style="height: 100%">
                        <div class="movie-hover-background"></div>
                        <div class="row" style="height: 100%; padding-top: 100px">
                            <div class="col col-lg-offset-1 col-lg-10">
                                <a id="@movie.ID" href="@Url.Action("Details", "Movie", new { movieID = movie.ID})" class="btn btn-primary btn-block" id="#">
                                    Les mer
                                </a>
                            </div>

                            <div class="col col-lg-offset-1 col-lg-10" style="padding-top: 15px">
                                <a id="@movie.ID" class="btn btn-success btn-block add-movie">
                                    Legg til i handlekurv
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
        </div>
    }
</div>
 