oslomet-film/Controllers/CartController.cs
using System.Web.Mvc;
using System.Linq;
using oslomet_film.Model;
using oslomet_film.BLL;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace oslomet_film.Controllers
{
    public class CartController : Controller
    {
        public ActionResult AddMovie(int movieID)
        {
            MovieBLL movieBLL = new MovieBLL();
            OrderBLL orderBLL = new OrderBLL();

            Cart cart = GetSessionCart();
            Movie movie = movieBLL.GetMovie(movieID);

            bool ownMovie = false; // False is user not logged in
            // Check if user is logged in
            Customer customer = (Customer)Session["customer"];
            if (customer != null)
            {
                ownMovie = orderBLL.OwnsMovie(customer, movie);
            }

            if (!InCart(movie, cart) || ownMovie)
            {
                CartItem item = new CartItem()
                {
                    Movie = movie,
                    Price = movie.Price
                };
                cart.CartItem.Add(item);
            }
            
            ViewBag.Total = GetTotal();
            return PartialView("CartPartial", cart.CartItem.ToList());
        }
        public ActionResult CompleteOrder()
        {
            OrderBLL orderBLL = new OrderBLL();

            Customer customer = (Customer)Session["customer"];
            if(customer == null)
            {
                // User must be logged in
                return null;
            }

            orderBLL.CreateOrder(customer, GetSessionCart());
            Session["cart"] = null;
            return Content("Success");
        } 

        public ActionResult GetCart()
        {
            ViewBag.Total = GetTotal();
            Cart cart = GetSessionCart();
            return PartialView("CartPartial", cart.CartItem.ToList());
        }

        public ActionResult GetCartFull()
        {
            Cart cart = GetSessionCart();
            ViewBag.Total = GetTotal();
            return View(cart.CartItem.ToList());
        }

        //Removing item from CartItems List in Cart
        public ActionResult RemoveItem(int movieID)
        {
            Cart cart = GetSessionCart();
            cart.CartItem.RemoveAll(ci => ci.Movie.ID == movieID);
            return View("index", GetSessionCart());
        }
        

        // GET: Cart
        public ActionResult Index()
        {
            ViewBag.Total = GetTotal();
            return View(GetSessionCart());
        }

        public Cart GetSessionCart()
        {
            Cart cart = (Cart)Session["cart"];

            if (cart != null) {
                return cart;
            }

            cart = new Cart
            {
                CartItem = new List<CartItem>()
            };
            Session["cart"] = cart;
            return cart;
        }

        private int GetTotal()
        {
            int total = 0;
            Cart cart = GetSessionCart();
            foreach(CartItem item in cart.CartItem) {
                total += item.Price;
            }
            return total;
        }

        
        private bool InCart(Movie movie, Cart cart)
        {
            foreach(CartItem item in cart.CartItem)
            {
                if (item.Movie.ID == movie.ID) return true;
            }
            return false;
        }
    }
}

oslomet-film/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using oslomet_film.BLL;
using oslomet_film.Model;

namespace oslomet_film.Controllers
{
    public class CustomerController : Controller
    {
        // GET: Customer
        public ActionResult DisplayCustomers()
        {
            var customerBLL = new CustomerBLL();
            List<Customer> displayAllCustomers = customerBLL.getAll();
            return View(displayAllCustomers);
        }

        public ActionResult Register()
        {
            Customer customerModel = new Customer();
            return View(customerModel);
        }

        [HttpPost]
        public ActionResult Register(Customer customerModel)
        {
            var customerBLL = new CustomerBLL();
            bool userAdded = customerBLL.addCustomer(customerModel);
            if (userAdded)
            {
                ViewBag.RegistrationSuccess = "Registration successfull!";
                bool loginSuccess = customerBLL.login(customerModel);
                Customer customerSession = customerBLL.fetchCustomerByUsername(customerModel.Username);

                if (loginSuccess)
                {
                    ViewBag.LoginSuccess = "Login successfull!";
                    Session["customerID"] = customerSession.ID;
                    Sessions();
                    return RedirectToAction("../Home/Index");
                }
            }
            ViewBag.RegistrationFailed = "Registration Failed";
            return View(customerModel);
        }

        public ActionResult Login()
        {
            Customer loginModel = new Customer();
            return View(loginModel);
        }

        [HttpPost]
        public ActionResult Login(Customer loginModel)
        {
            var customerBLL = new CustomerBLL();
            bool loginSuccess = customerBLL.login(loginModel);
            Customer customerSession = customerBLL.fetchCustomerByUsername(loginModel.Username);

            if (loginSuccess)
                {
                Session["customerID"] = customerSession.ID;
                ViewBag.LoginSuccess = "Login successfull!";
                Sessions();

                if (customerSession.Admin == true)
                {
                    Session["Admin"] = customerSession; 
                    return RedirectToAction("Index", "Dashboard");
                } 
                    return RedirectToAction("../Home/Index");
                }
            ViewBag.LoginFailed = "Login failed";
            return View(loginModel);
        }

        public ActionResult EditUser()
        {
            int id = (int)Session["customerID"];
            var customerBLL = new CustomerBLL();
            Customer editModel = customerBLL.fetchCustomer(id);
            return View(editModel);
        }

        [HttpPost]
        public ActionResult EditUser(int id, Customer editModel)
        {
            var customerBLL = new CustomerBLL();
            bool editSuccess = customerBLL.editUser(id, editModel);
            if (editSuccess)
            {
                ViewBag.EditSuccessfull = "Edit Successfull";
                Sessions();
                return View(editModel);
            }
            ViewBag.EditFailed = "Edit failed";
            return View(editModel);
        }

        public void Sessions()
        {
            int id = (int)Session["customerID"];
            var customerBLL = new CustomerBLL();
            Customer customerDetails = customerBLL.fetchCustomer(id);

            if(customerDetails.Admin == true)
            {
                Session["Admin"] = customerDetails;
            } else
            {
                Session["Admin"] = null;
            }

            Session["customer"] = customerDetails;
            Session["userName"] = customerDetails.Username;
            var customer = (Customer)Session["customer"];
            string userName = (string)Session["userName"];
        }

        public ActionResult FetchCustomer(int id)
        {
            var customerBLL = new CustomerBLL();
            Customer customerDetails = customerBLL.fetchCustomer(id);
            return View(customerDetails);
        }

        public ActionResult Logout()
        {
            Session.Abandon();
            return RedirectToAction("../Home/Index");
        }
    }
}

oslomet-film/Controllers/ProfileController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using oslomet_film.BLL;
using oslomet_film.Model;

namespace oslomet_film.Controllers
{
    public class ProfileController : Controller
    {
        // GET: Profile
        public ActionResult Index()
        {
            MovieBLL movieBLL = new MovieBLL();

            Customer customer = (Customer)Session["customer"];
            if (customer == null) return null;

            List<Movie> movies = movieBLL.GetMyMovies(customer);
            return View(movies);
        }
    }
}

oslomet-film/Views/Shared/AdminSideMenu.cshtml
<div class="navbar">
    <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav navbar-left">
            <li>@Html.ActionLink("Alle Filmer", "Allmovies", "Dashboard")</li>
            <li>@Html.ActionLink("Alle Brukere", "AllCustomers", "Dashboard")</li>
            <li>@Html.ActionLink("Alle Ordre", "AllOrders", "Dashboard")</li>
            <li>@Html.ActionLink("Legg til Film", "AddMovie", "Dashboard")</li>
            <li>@Html.ActionLink("Legg til Bruker", "Register", "Dashboard")</li>
        </ul>
    </div>
</div>

oslomet-film/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Oslomet Film</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Oslomet-film", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    @if (Session["customer"] == null)
                    {
                    <li>@Html.ActionLink("Register", "Register", "Customer")</li> 
                    <li>@Html.ActionLink("Log in", "Login", "Customer")</li>

                    }
                    else if(Session["Admin"] != null)
                    {
                        <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" style="text-transform: capitalize;">
                                @Session["userName"]
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Dashboard", "Index", "Dashboard") </li>
                                <li>@Html.ActionLink("Log out", "Logout", "Customer")</li>
                            </ul>
                        </li>

                    } else if(Session["customer"] != null)
                    {
                        <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" style="text-transform: capitalize;">
                                @Session["userName"]
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Mine Filmer", "Index", "Profile")</li>
                                <li>@Html.ActionLink("Edit user", "EditUser", "Customer") </li>
                                <li>@Html.ActionLink("Log out", "Logout", "Customer")</li>
                            </ul>
                        </li>
                    }

                    <li id="cart">
                        @if (Session["cart"] != null)
                        {
                            Html.RenderAction("GetCart", "Cart");
                        }
                    </li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        <div>
            <div id="cart">

            </div>
        </div>
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year Oslomet Film</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/main.js"></script>
</body>
</html>